"""
Convert Open Iconic 8x8 PNGs to MicroPython bytearray bitmaps.

Open Iconic: https://github.com/iconic/open-iconic
License:     MIT (icons), SIL OFL 1.1 (font)

Usage:
    python convert_icons.py <path/to/open-iconic/png> <output.py>

Reads 8x8 PNGs and emits a Python module with MSB-left bitmaps suitable for
the firefly_oled_v2.py driver (draws bitmaps as ssd1306.pixel() calls).
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image


# Icon concept → Open Iconic filename (base 8x8 PNG, no size suffix)
ICON_MAP: dict[str, str] = {
    # Resource meters
    "CPU": "pulse",                    # activity/compute — closest to CPU in Open Iconic
    "MEM": "layers",                   # stacked layers ≈ memory banks
    "DSK": "hard-drive",               # direct match
    # Seed bank indicator (plugged volume)
    "USB": "bolt",                     # lightning bolt = active/connected
    # Right-panel info
    "GEAR": "cog",                     # services/offerings
    "NET_DOWN": "data-transfer-download",
    "NET_UP": "data-transfer-upload",
    "NET": "globe",                    # combined throughput — network glyph
    "CLOCK": "clock",                  # uptime
    "STONES": "grid-three-up",         # garden topology
    # Health states
    "THRIVING": "heart",               # healthy
    "WITHERING": "warning",            # warning triangle
    "WILTING": "circle-x",             # error cross
}


def png_to_bitmap(png_path: Path) -> list[int]:
    """Convert an 8x8 PNG to 8 bytes of MSB-left bitmap data.

    Open Iconic PNGs are black-on-transparent: opaque pixels = icon, transparent = background.
    """
    img = Image.open(png_path).convert("RGBA")
    if img.size != (8, 8):
        img = img.resize((8, 8), Image.Resampling.LANCZOS)

    rows: list[int] = []
    for y in range(8):
        byte = 0
        for x in range(8):
            r, g, b, a = img.getpixel((x, y))
            # Pixel is "on" if opaque and dark (icon foreground)
            is_on = a > 127 and (r + g + b) < 384
            if is_on:
                byte |= 0x80 >> x
        rows.append(byte)
    return rows


def render_ascii(rows: list[int]) -> str:
    """Render an 8x8 bitmap as ASCII art for visual verification."""
    lines = []
    for byte in rows:
        line = ""
        for x in range(8):
            line += "##" if byte & (0x80 >> x) else "  "
        lines.append(line)
    return "\n".join(lines)


def bytearray_literal(name: str, rows: list[int]) -> str:
    """Format an icon as a Python bytearray literal with visual comments."""
    lines = [f"ICON_{name} = bytearray(["]
    for byte in rows:
        visual = "".join("#" if byte & (0x80 >> x) else "." for x in range(8))
        lines.append(f"    0x{byte:02X},  # {visual}")
    lines.append("])")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 1

    png_dir = Path(sys.argv[1])
    output = Path(sys.argv[2])

    if not png_dir.is_dir():
        print(f"error: {png_dir} is not a directory", file=sys.stderr)
        return 1

    sections: list[str] = []
    sections.append('"""')
    sections.append("Open Iconic bitmaps for Firefly OLED v2.")
    sections.append("")
    sections.append("Auto-generated by firmware/firefly/tools/convert_icons.py")
    sections.append("Do not edit by hand — re-run the converter to regenerate.")
    sections.append("")
    sections.append("Source: https://github.com/iconic/open-iconic")
    sections.append("License: MIT (icons), SIL OFL 1.1 (font form)")
    sections.append("")
    sections.append("Each icon is an 8-byte MSB-left bitmap (8x8 pixels).")
    sections.append('"""')
    sections.append("")

    for name, source in ICON_MAP.items():
        png_path = png_dir / f"{source}.png"
        if not png_path.exists():
            print(f"warning: missing {png_path}", file=sys.stderr)
            continue

        rows = png_to_bitmap(png_path)
        sections.append(f"# {source}.png")
        sections.append(bytearray_literal(name, rows))
        sections.append("")

        # Also print ASCII preview to stderr
        print(f"\n=== {name} ({source}.png) ===", file=sys.stderr)
        print(render_ascii(rows), file=sys.stderr)

    output.write_text("\n".join(sections), encoding="utf-8")
    print(f"\nWrote {output} ({len(ICON_MAP)} icons)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
