//! Linux-specific install and uninstall logic (systemd)

use std::path::Path;
use std::process::Command;

use super::SERVICE_NAME;

pub(crate) const UNIT_FILE_PATH: &str = "/etc/systemd/system/garden-moss.service";
const BIN_DIR: &str = "/usr/local/bin";

/// Linux binaries to install from package bin/ directory
const BINARIES: &[&str] = &["garden-moss", "garden-rake", "garden-lantern"];

/// Legacy scripts — no longer shipped in packages (BUILD-0003).
/// `pre-start` subcommand replaces `moss-update-helper.sh`.
/// `garden-upgrade.sh` was deprecated and removed.
const SCRIPTS: &[&str] = &[];

/// Full paths to legacy shell scripts left behind by the old updater.
/// `pre-start` and `ensure_modern_unit_file` remove these on first boot
/// after receiving the new binary.
pub(crate) const LEGACY_SCRIPTS: &[&str] = &[
    "/usr/local/bin/moss-update-helper.sh",
    "/usr/local/bin/garden-upgrade.sh",
];

/// Install on Linux: deploy binaries, scripts, systemd unit, create directories.
pub fn install_platform(staging_dir: &Path) -> anyhow::Result<()> {
    // Create data and config directories
    create_directories()?;

    // Find the package contents (may be inside a subdirectory)
    let bin_dir = find_bin_dir(staging_dir);

    // Install binaries
    install_binaries(&bin_dir)?;

    // Install companions subdirectory if present
    install_companions(&bin_dir)?;

    // Note: scripts/ directory no longer shipped in packages (BUILD-0003).
    // System config files are generated by the binary (generate_unit_file, provision).
    // Legacy packages with scripts/ still work — install_scripts() handles them gracefully.

    // Install systemd service
    install_service_unit()?;

    Ok(())
}

fn create_directories() -> anyhow::Result<()> {
    let data = garden_common::constants::paths::data_dir();
    let config = garden_common::constants::paths::config_dir();

    println!("  Creating directories...");
    std::fs::create_dir_all(&data)?;
    println!("    {}", data);
    std::fs::create_dir_all(&config)?;
    println!("    {}", config);

    Ok(())
}

/// Find the bin/ directory inside the extracted package.
/// Packages extract as: staging/zen-garden-{version}/bin/ or staging/bin/
fn find_bin_dir(staging_dir: &Path) -> std::path::PathBuf {
    // Direct bin/ in staging
    let direct = staging_dir.join("bin");
    if direct.exists() {
        return direct;
    }

    // Inside a version subdirectory: staging/zen-garden-*/bin/
    if let Ok(entries) = std::fs::read_dir(staging_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            if entry.path().is_dir() {
                let nested = entry.path().join("bin");
                if nested.exists() {
                    return nested;
                }
            }
        }
    }

    // Fallback: staging dir itself (flat layout)
    staging_dir.to_path_buf()
}

fn install_binaries(bin_dir: &Path) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;

    println!("  Installing binaries...");

    for name in BINARIES.iter().chain(SCRIPTS.iter()) {
        let src = bin_dir.join(name);
        let dest = Path::new(BIN_DIR).join(name);

        if src.exists() {
            replace_binary(&src, &dest)?;
            std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o755))?;
            println!("    {} -> {}", name, dest.display());
        }
    }

    Ok(())
}

fn install_companions(bin_dir: &Path) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;

    let companions_src = bin_dir.join("companions");
    if !companions_src.exists() {
        return Ok(());
    }

    let companions_dest = Path::new(BIN_DIR).join("companions");
    std::fs::create_dir_all(&companions_dest)?;

    println!("  Installing companions...");

    if let Ok(entries) = std::fs::read_dir(&companions_src) {
        for entry in entries.filter_map(|e| e.ok()) {
            let src = entry.path();
            let dest = companions_dest.join(entry.file_name());
            if src.is_file() {
                replace_binary(&src, &dest)?;
                std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o755))?;
                println!("    companions/{}", entry.file_name().to_string_lossy());
            }
        }
    }

    Ok(())
}

/// Replace a binary file using rename-then-copy to avoid ETXTBSY (errno 26).
///
/// On Linux, `open(O_WRONLY)` on a running executable returns ETXTBSY.
/// `rename(2)` atomically detaches the directory entry while the kernel
/// keeps the old inode alive for any process still mapping it.
/// The copy then creates a fresh inode at the original path.
fn replace_binary(src: &Path, dest: &Path) -> anyhow::Result<()> {
    use anyhow::Context;

    if dest.exists() {
        let backup = dest.with_extension("old");
        std::fs::rename(dest, &backup).with_context(|| {
            format!(
                "failed to rename {} -> {} before copy",
                dest.display(),
                backup.display()
            )
        })?;
        let result = std::fs::copy(src, dest).with_context(|| {
            format!("failed to copy {} -> {}", src.display(), dest.display())
        });
        let _ = std::fs::remove_file(&backup);
        result?;
    } else {
        std::fs::copy(src, dest).with_context(|| {
            format!("failed to copy {} -> {}", src.display(), dest.display())
        })?;
    }
    Ok(())
}

fn install_service_unit() -> anyhow::Result<()> {
    println!("  Installing service...");

    // Generate the unit file content
    let unit_contents = generate_unit_file();
    std::fs::write(UNIT_FILE_PATH, unit_contents)?;
    println!("    {} -> {}", "garden-moss.service", UNIT_FILE_PATH);

    // Reload systemd
    print!("    systemctl daemon-reload...");
    match Command::new("systemctl").args(["daemon-reload"]).output() {
        Ok(o) if o.status.success() => println!(" done."),
        Ok(o) => println!(" warning: {}", String::from_utf8_lossy(&o.stderr).trim()),
        Err(e) => println!(" warning: {e}"),
    }

    // Enable (start on boot)
    match Command::new("systemctl")
        .args(["enable", SERVICE_NAME])
        .output()
    {
        Ok(o) if o.status.success() => println!("    Service enabled (start on boot)"),
        Ok(o) => println!(
            "    Warning: could not enable service: {}",
            String::from_utf8_lossy(&o.stderr).trim()
        ),
        Err(e) => println!("    Warning: could not enable service: {e}"),
    }

    Ok(())
}

pub(crate) fn generate_unit_file() -> String {
    // Generated by garden-moss install — no external template needed (BUILD-0003)
    format!("\
[Unit]
Description=Garden Moss Daemon - Zen Garden Stone Manager
Documentation=https://github.com/koan-framework/zen-garden
After=network-online.target docker.service avahi-daemon.service
Wants=network-online.target
Wants=docker.service

[Service]
Type=notify
User=root
Group=root
NotifyAccess=main
WatchdogSec=60
TimeoutStartSec=300
TimeoutStopSec=20
ExecStartPre=/usr/local/bin/garden-moss pre-start
ExecStart=/usr/local/bin/garden-moss
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=garden-moss

# Environment
Environment=\"RUST_LOG=info\"
Environment=\"PORT={port}\"

# Resource limits
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
", port = garden_common::constants::MOSS_HTTP)
}

// ── Uninstall ────────────────────────────────────────────────────────

pub fn uninstall_platform() -> anyhow::Result<()> {
    // Stop service if running
    if systemctl_check("is-active") {
        print!("  Stopping service...");
        let _ = Command::new("systemctl")
            .args(["stop", SERVICE_NAME])
            .output();
        println!(" done.");
    }

    // Disable service
    if systemctl_check("is-enabled") {
        match Command::new("systemctl")
            .args(["disable", SERVICE_NAME])
            .output()
        {
            Ok(o) if o.status.success() => println!("  Service disabled."),
            _ => {}
        }
    }

    // Remove unit file
    let unit_path = Path::new(UNIT_FILE_PATH);
    if unit_path.exists() {
        print!("  Removing {}...", UNIT_FILE_PATH);
        match std::fs::remove_file(unit_path) {
            Ok(()) => println!(" done."),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => println!(" already removed."),
            Err(e) => println!(" warning: {e}"),
        }

        // Reload systemd
        let _ = Command::new("systemctl").args(["daemon-reload"]).output();
    }

    // Remove binaries
    println!("  Removing binaries...");
    for name in BINARIES {
        let path = Path::new(BIN_DIR).join(name);
        if path.exists() {
            match std::fs::remove_file(&path) {
                Ok(()) => println!("    {}", path.display()),
                Err(e) => println!("    {} (warning: {e})", path.display()),
            }
        }
    }

    // Remove legacy scripts (full paths)
    for path_str in LEGACY_SCRIPTS {
        let path = Path::new(path_str);
        if path.exists() {
            match std::fs::remove_file(path) {
                Ok(()) => println!("    {}", path.display()),
                Err(e) => println!("    {} (warning: {e})", path.display()),
            }
        }
    }

    // Remove companions directory
    let companions_dir = Path::new(BIN_DIR).join("companions");
    if companions_dir.exists() {
        match std::fs::remove_dir_all(&companions_dir) {
            Ok(()) => println!("    {}/", companions_dir.display()),
            Err(e) => println!("    {}/ (warning: {e})", companions_dir.display()),
        }
    }

    Ok(())
}

fn systemctl_check(query: &str) -> bool {
    Command::new("systemctl")
        .args([query, SERVICE_NAME])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}
