//! Pond security API handlers
//!
//! Translates zen-garden Pond vocabulary to koi-certmesh operations.
//! All cryptographic work is delegated to certmesh — these handlers
//! are a thin domain-vocabulary facade.
//!
//! Security model:
//! - CA (keystone) creation requires a passphrase
//! - Enrollment uses TOTP codes shared out-of-band
//! - Auto-unlock: JustMe/MyTeam profiles save passphrase to disk and
//!   unlock automatically on reboot. MyOrganization profiles stay locked.
//! - All cert lifecycle managed by certmesh (issue, renew, revoke)

use crate::{
    Moss, bad_gateway, bad_request, conflict, error_response, forbidden, internal, not_found,
    unavailable,
};
use crate::domain::security::renewal::{POND_RENEW_PATH, PondRenewRequest, PondRenewResponse};
use axum::{
    Json,
    body::Bytes,
    extract::{Path, State},
    http::{HeaderMap, StatusCode},
    response::Html,
};
use garden_common::api_utils::ApiErrorResponse;
use serde::{Deserialize, Serialize};
use tower::ServiceExt;

/// Embedded pond ceremony UI — single-page app served at `/pond`
const POND_HTML: &str = include_str!("../../../assets/pond.html");

// ============================================================================
// Request types
// ============================================================================

#[derive(Deserialize)]
pub struct PondInitRequest {
    /// Passphrase to encrypt the CA private key at rest.
    /// If empty and `generate_passphrase` is true, an XKCD-style passphrase is generated.
    #[serde(default)]
    pub passphrase: String,
    /// Generate an XKCD-style passphrase (word-word-word-NN) instead of requiring one.
    /// The generated passphrase is returned in the response.
    #[serde(default)]
    pub generate_passphrase: bool,
    /// Trust profile: "just-me" (default), "my-team", "my-organization"
    #[serde(default)]
    pub profile: Option<String>,
    /// Optional pond name (auto-generated if omitted)
    #[serde(default)]
    pub name: Option<String>,
}

#[derive(Deserialize)]
pub struct PondRenameRequest {
    /// New pond name (must match pond-{word}-{word} format, or omit to auto-generate)
    #[serde(default)]
    pub name: Option<String>,
}

#[derive(Deserialize)]
pub struct PondJoinRequest {
    /// TOTP code from the authenticator app
    pub code: String,
    /// Override hostname for this enrollment (default: system hostname)
    #[serde(default)]
    pub hostname: Option<String>,
    /// Additional SANs for the certificate (e.g. extra IPs)
    #[serde(default)]
    pub sans: Vec<String>,
    /// PKCS#10 CSR (PEM) generated by the joining stone's Moss (koi CSR-only
    /// enrollment, ADR-015). Absent on the rake→joiner hop; the joining Moss
    /// generates it via `prepare_member_csr` and populates it when forwarding to
    /// the cornerstone. The CA signs it and never sees the member private key.
    #[serde(default)]
    pub csr: Option<String>,
}

#[derive(Deserialize)]
pub struct PondUnlockRequest {
    /// Passphrase to decrypt the CA private key (passphrase unlock)
    #[serde(default)]
    pub passphrase: Option<String>,
    /// TOTP code for authenticator-based unlock
    #[serde(default)]
    pub totp_code: Option<String>,
}

#[derive(Deserialize)]
pub struct PondInviteRequest {
    /// Passphrase needed to rotate the enrollment auth
    pub passphrase: String,
    /// Enrollment window duration in minutes (default: 30)
    #[serde(default)]
    pub ttl_minutes: Option<u64>,
}

#[derive(Deserialize)]
pub struct PondPromoteRequest {
    /// Client's X25519 public key for key exchange (hex-encoded, 32 bytes)
    pub client_public_key: String,
}

// ============================================================================
// Response types
// ============================================================================

#[derive(Serialize)]
pub struct PondInitResponse {
    pub cornerstone: String,
    pub keystone_path: String,
    pub certificate_expires: String,
    pub status: String,
    pub totp_uri: Option<String>,
    pub ca_fingerprint: String,
    pub name: String,
    /// Generated passphrase (only present when `generate_passphrase` was true)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_passphrase: Option<String>,
    /// Memorization hint for the generated passphrase
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memorization_hint: Option<String>,
}

#[derive(Serialize)]
pub struct PondInviteResponse {
    pub totp_uri: String,
    pub expires_at: Option<String>,
    pub ttl_seconds: Option<u64>,
    pub inviter_stone: String,
    pub enrollment_state: String,
}

#[derive(Serialize, Deserialize)]
pub struct PondJoinResponse {
    pub stone_name: String,
    pub cornerstone: Option<String>,
    pub certificate_expires: String,
    pub status: String,
    pub ca_fingerprint: String,
    /// PEM-encoded CA certificate (populated by cornerstone for proxy enrollment).
    /// The joining Moss installs this next to its locally-held key (CSR-only model);
    /// the CA never returns a private key.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub ca_cert: Option<String>,
    /// PEM-encoded signed service certificate (populated by cornerstone for proxy enrollment)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub service_cert: Option<String>,
}

#[derive(Serialize)]
pub struct PondStatusResponse {
    pub active: bool,
    pub locked: bool,
    pub name: Option<String>,
    pub cornerstone: Option<String>,
    pub stones: Vec<PondStoneInfo>,
    pub profile: String,
    pub ca_fingerprint: Option<String>,
    pub enrollment_state: String,
    /// This stone's own trust identity health (posture + leaf expiry).
    pub identity: PondIdentity,
}

#[derive(Serialize)]
pub struct PondStoneInfo {
    pub name: String,
    pub role: String,
    pub status: String,
    pub certificate_expires: String,
    pub joined_at: Option<String>,
}

/// This stone's own trust identity — whether it holds a usable identity, whether
/// it is the cornerstone (holds the CA), and how long its leaf remains valid. The
/// warm "do I belong, and am I still trusted?" signal behind `pond status`.
#[derive(Serialize)]
pub struct PondIdentity {
    /// A usable cryptographic identity is present (Authenticated posture).
    pub signed: bool,
    /// This stone holds the pond CA (it is the keystone), not a member leaf.
    pub is_cornerstone: bool,
    /// RFC3339 expiry of this stone's leaf. `None` only when no identity / the
    /// leaf cannot be parsed.
    pub expires_at: Option<String>,
    /// Days until this stone's leaf expires (negative once expired). `None` when
    /// `expires_at` is `None`.
    pub expires_in_days: Option<i64>,
}

// ============================================================================
// Common result type
// ============================================================================

type PondResult<T> = crate::api::ApiResult<T>;

/// Map koi CertmeshError to HTTP error response
fn certmesh_err(e: koi_certmesh::CertmeshError) -> (StatusCode, Json<ApiErrorResponse>) {
    use koi_certmesh::CertmeshError;
    match e {
        CertmeshError::CaNotInitialized => conflict(
            "POND_NOT_INITIALIZED",
            "Pond not initialized. Run 'garden-rake place keystone' first.",
        ),
        CertmeshError::CaLocked => error_response(
            StatusCode::LOCKED,
            "POND_LOCKED",
            "Pond is locked. Run 'garden-rake pond unlock' after restart.",
            None,
        ),
        CertmeshError::InvalidAuth => error_response(
            StatusCode::UNAUTHORIZED,
            "INVALID_AUTH",
            "Invalid passphrase or TOTP code.",
            None,
        ),
        CertmeshError::RateLimited { remaining_secs } => error_response(
            StatusCode::TOO_MANY_REQUESTS,
            "RATE_LIMITED",
            format!("Too many failed attempts. Try again in {remaining_secs}s."),
            None,
        ),
        CertmeshError::EnrollmentClosed => forbidden(
            "ENROLLMENT_CLOSED",
            "Enrollment is closed. Ask the keystone operator to run 'garden-rake pond invite'.",
        ),
        CertmeshError::AlreadyEnrolled(hostname) => conflict(
            "ALREADY_ENROLLED",
            format!("Stone '{hostname}' is already enrolled in the pond."),
        ),
        CertmeshError::NotFound(what) => not_found("NOT_FOUND", format!("Not found: {what}")),
        CertmeshError::Revoked(hostname) => forbidden(
            "REVOKED",
            format!("Stone '{hostname}' has been revoked from the pond."),
        ),
        CertmeshError::ApprovalDenied => forbidden(
            "APPROVAL_DENIED",
            "Enrollment request was denied by the operator.",
        ),
        CertmeshError::NoSlotFound(detail) => bad_request("NO_SLOT_FOUND", detail.to_string()),
        _ => {
            // Sanitise: strip internal Rust error chains, log the full detail
            let full = format!("{e}");
            tracing::warn!(error = %full, "Certmesh operation failed");
            internal(
                "CERTMESH_ERROR",
                "An internal error occurred. Check server logs for details.",
            )
        }
    }
}

/// Get the CertmeshCore from Moss, returning appropriate HTTP errors
fn get_certmesh_core(
    state: &Moss,
) -> Result<std::sync::Arc<koi_certmesh::CertmeshCore>, (StatusCode, Json<ApiErrorResponse>)> {
    let handle = state.discovery.koi().certmesh().map_err(|e| {
        unavailable(
            "CERTMESH_UNAVAILABLE",
            format!("Certmesh subsystem not available: {e}"),
        )
    })?;
    handle.core().map_err(|e| {
        unavailable(
            "CERTMESH_CORE_UNAVAILABLE",
            format!("Certmesh core not ready: {e}"),
        )
    })
}

/// Refresh the pond_active flag from certmesh state.
///
/// Delegates to domain function. Kept as a thin wrapper so existing callers
/// in this module continue to work without a path change.
async fn refresh_pond_active(state: &Moss) {
    crate::domain::security::pond_lifecycle::refresh_pond_active(state).await;
}

/// Notify the system that enrollment state changed.
///
/// Delegates to domain function. Kept as a thin wrapper so existing callers
/// in this module continue to work without a path change.
async fn notify_enrollment_changed(state: &Moss, enrolled: bool, cornerstone: Option<String>) {
    crate::domain::security::pond_lifecycle::notify_enrollment_changed(
        state,
        enrolled,
        cornerstone,
    )
    .await;
}

// ============================================================================
// Handlers
// ============================================================================

/// GET /pond — Serve the embedded pond ceremony web UI
pub async fn get_pond_page() -> (
    StatusCode,
    [(&'static str, &'static str); 1],
    Html<&'static str>,
) {
    (
        StatusCode::OK,
        [("content-type", "text/html; charset=utf-8")],
        Html(POND_HTML),
    )
}

/// POST /api/v1/pond/init — Place keystone (create CA)
///
/// Creates the certificate authority for this garden. The calling stone
/// becomes the cornerstone (primary CA holder). Returns a TOTP URI for
/// the authenticator app — this is used to authorize future stone enrollments.
pub async fn pond_init_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondInitRequest>,
) -> PondResult<PondInitResponse> {
    use crate::domain::security::pond_lifecycle::{self, PondInitInput};

    let core = get_certmesh_core(&state)?;

    // Generate passphrase if requested (or if passphrase is empty)
    let (passphrase, generated_passphrase, memorization_hint) =
        if payload.generate_passphrase || payload.passphrase.is_empty() {
            let entropy = koi_certmesh::entropy::collect_entropy(
                koi_certmesh::entropy::EntropyMode::AutoGenerate,
            )
            .map_err(|e| internal("ENTROPY_FAILED", format!("Entropy collection failed: {e}")))?;
            let generated = koi_certmesh::entropy::generate_passphrase(&entropy);
            let hint = koi_certmesh::entropy::memorization_hint(&generated);
            (generated.clone(), Some(generated), Some(hint))
        } else {
            (payload.passphrase, None, None)
        };

    let input = PondInitInput {
        passphrase,
        profile: payload.profile,
        name: payload.name,
    };

    let result = pond_lifecycle::init(&state, core, input)
        .await
        .map_err(|e| {
            let msg = format!("{e}");
            if msg.contains("Unknown trust profile") {
                bad_request("INVALID_PROFILE", msg)
            } else {
                internal("POND_INIT_FAILED", msg)
            }
        })?;

    crate::api::ok(PondInitResponse {
        cornerstone: result.cornerstone,
        keystone_path: result.keystone_path,
        certificate_expires: "30 days".to_string(),
        status: "active".to_string(),
        totp_uri: result.totp_uri,
        ca_fingerprint: result.ca_fingerprint,
        name: result.pond_name,
        generated_passphrase,
        memorization_hint,
    })
}

/// GET /api/v1/pond/status — Get pond status and membership
pub async fn pond_status_v1(State(state): State<Moss>) -> PondResult<PondStatusResponse> {
    let core = get_certmesh_core(&state)?;
    let status = core.certmesh_status().await;

    let active = status.ca_initialized && !status.ca_locked;
    let cornerstone = status
        .members
        .iter()
        .find(|m| m.role == "primary")
        .map(|m| m.hostname.clone());

    let stones: Vec<PondStoneInfo> = status
        .members
        .iter()
        .map(|m| PondStoneInfo {
            name: m.hostname.clone(),
            role: m.role.clone(),
            status: m.status.clone(),
            certificate_expires: m.cert_expires.clone(),
            joined_at: None,
        })
        .collect();

    // This stone's own identity health. Read the leaf's renewal schedule from the
    // local identity (cert-derived — works for both a member and the cornerstone,
    // and does not depend on koi's member.json renewal state, which zen does not
    // arm). `member_cert_expiry()` is member.json-gated and would be `None` for a
    // zen member, so it is deliberately not used here.
    let local = core.local_identity().await;
    let identity = PondIdentity {
        signed: core.posture().signed,
        is_cornerstone: status.ca_initialized,
        expires_at: local
            .as_ref()
            .map(|id| id.renewal.expires_at.to_rfc3339()),
        expires_in_days: local.as_ref().map(|id| id.renewal.expires_in_days),
    };

    crate::api::ok(PondStatusResponse {
        active,
        locked: status.ca_initialized && status.ca_locked,
        name: state.security.pond_name().await,
        cornerstone,
        stones,
        profile: trust_profile_label(status.enrollment_open, status.requires_approval).to_string(),
        ca_fingerprint: status.ca_fingerprint,
        enrollment_state: format!("{:?}", status.enrollment_state),
        identity,
    })
}

/// Derive a display label for the trust posture from the two booleans certmesh
/// stores. The inverse of koi's preset table; `(open, approval)` that matches no
/// named preset reads as "custom".
fn trust_profile_label(enrollment_open: bool, requires_approval: bool) -> &'static str {
    match (enrollment_open, requires_approval) {
        (true, false) => "just-me",
        (true, true) => "my-team",
        (false, true) => "my-organization",
        (false, false) => "custom",
    }
}

// ============================================================================
// Signing oracle (LOOPBACK ONLY)
// ============================================================================

#[derive(Deserialize)]
pub struct PondSignRequest {
    /// HTTP method of the request to be signed (e.g. "POST").
    pub method: String,
    /// Request path + query verbatim (e.g. "/api/v1/stone/services?x=1").
    pub path: String,
    /// Destination stone name — the audience the signature is bound to.
    pub audience: String,
    /// blake3 hex of the request body (`garden_common::pond::body_hash_hex`); the
    /// body itself never travels to this oracle.
    pub body_hash: String,
}

#[derive(Serialize)]
pub struct PondSignResponse {
    /// The koi clear-signed envelope to attach as the `X-Koi-Envelope` header.
    pub envelope: koi_common::envelope::Envelope,
    /// `true` when actually signed (Authenticated posture); `false` when this
    /// stone holds no identity yet (Open passthrough — the target sees anonymous).
    pub signed: bool,
}

/// POST /api/v1/pond/sign — sign canonical request bytes with this stone's
/// identity, returning a koi clear-signed envelope for `rake` to attach.
///
/// ⚠️ **Impersonation oracle — loopback only.** This is served *exclusively* on
/// `127.0.0.1:MOSS_SIGN_LOOPBACK` by [`crate::bootstrap::sign_listener`], never on
/// the `0.0.0.0` API listeners. Anyone who can reach it can make Moss vouch for
/// this stone, so it must never be exposed off-host. It is deliberately absent
/// from `router::configure`/`configure_public`.
///
/// The signature covers the canonical bytes (verb + path + audience + body hash);
/// the verifier rebuilds the same bytes from the request it actually receives, so
/// a signature cannot be lifted to another operation, body, or stone.
pub async fn pond_sign_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondSignRequest>,
) -> PondResult<PondSignResponse> {
    let canonical = garden_common::pond_authz::canonical_request_bytes(
        &payload.method,
        &payload.path,
        &payload.audience,
        &payload.body_hash,
    );
    let envelope = state.discovery.koi().sign(&canonical).await.map_err(|e| {
        unavailable(
            "SIGN_UNAVAILABLE",
            format!("Could not sign request: {e}"),
        )
    })?;
    let signed = envelope.sig.is_some();
    crate::api::ok(PondSignResponse { envelope, signed })
}

// ============================================================================
// Renewal (zen-native, envelope-signed over the clear plane)
// ============================================================================
//
// The wire types (`POND_RENEW_PATH`, `PondRenewRequest`, `PondRenewResponse`)
// and the member-side renewal flow live in the security domain
// (`domain::security::renewal`), imported above. This handler is the CA-side
// verifier — the one place `core.verify` is consumed.

/// POST /api/v1/pond/renew — CA-side rotate-key renewal over the clear plane.
///
/// The member signs `{hostname, csr}` into a koi envelope (audience = this CA's
/// stone name) and POSTs it here. The CA:
/// 1. verifies the envelope → the authoritative signer CN (the one identity door);
/// 2. bind-checks that the envelope was signed for THIS request and THIS CSR — so
///    a captured envelope cannot be replayed with a swapped CSR to mint a cert for
///    the signer's identity bound to an attacker-held key (impersonation);
/// 3. renews via `core.renew_member`, which enforces roster membership, active
///    status, and SAN pinning against the verified CN (never the body's hostname).
///
/// An expired or unknown signer gets a structured "rejoin" response, not an
/// opaque 403 — a stone that went dark past its grace window is welcomed back.
pub async fn pond_renew_v1(
    State(state): State<Moss>,
    headers: HeaderMap,
    body: Bytes,
) -> PondResult<PondRenewResponse> {
    let core = get_certmesh_core(&state)?;

    // 1. Verify the envelope, then bind authorization to THIS request and THIS CSR
    //    in one step. `identity_for` returns the trusted CN only when the envelope is
    //    authenticated, fresh, AND its signed payload equals the canonical bytes of
    //    this exact request (audience = our name; the body hash covers the CSR). This
    //    is koi's request-binding door (ADR-022 M1) — it closes the silent-
    //    impersonation footgun where a captured envelope could be replayed at /renew
    //    with a swapped CSR.
    let envelope = parse_envelope_header(&headers)?;
    let assurance = core.verify(&envelope).await;
    let canonical = garden_common::pond_authz::canonical_request_bytes_for(
        "POST",
        POND_RENEW_PATH,
        &state.current.stone.name,
        &body,
    );
    let cn = match assurance.identity_for(&envelope, &canonical) {
        Some(cn) => cn.to_string(),
        None => return Err(reject_to_response(&assurance)),
    };

    // 2. Parse the CSR-bearing body (already proven to be exactly what was signed).
    let req: PondRenewRequest = serde_json::from_slice(&body).map_err(|e| {
        bad_request("INVALID_RENEW_BODY", format!("Malformed renew request: {e}"))
    })?;

    // 4. Renew. koi authorizes against `cn` (the verified signer), SAN-pinned.
    let renew = core.renew_member(&cn, &req.csr).await.map_err(certmesh_err)?;

    tracing::info!(stone = %cn, "Renewed pond member cert (envelope-authenticated)");

    crate::api::ok(PondRenewResponse {
        service_cert: renew.service_cert,
        ca_cert: renew.ca_cert,
        ca_fingerprint: renew.ca_fingerprint,
        expires: renew.expires,
    })
}

/// Parse the `X-Koi-Envelope` header into a koi [`Envelope`], or 401 when absent
/// or malformed.
fn parse_envelope_header(
    headers: &HeaderMap,
) -> Result<koi_common::envelope::Envelope, (StatusCode, Json<ApiErrorResponse>)> {
    let raw = headers
        .get(garden_common::constants::headers::HEADER_KOI_ENVELOPE)
        .and_then(|v| v.to_str().ok())
        .ok_or_else(|| {
            error_response(
                StatusCode::UNAUTHORIZED,
                "ENVELOPE_MISSING",
                "This operation requires a signed request (no X-Koi-Envelope header).",
                None,
            )
        })?;
    serde_json::from_str(raw).map_err(|e| {
        error_response(
            StatusCode::UNAUTHORIZED,
            "ENVELOPE_MALFORMED",
            format!("Could not parse the signed envelope: {e}"),
            None,
        )
    })
}

/// Map a non-identity [`Assurance`] to an HTTP error. An expired or unknown
/// signer is a warm `POND_REJOIN_REQUIRED`, not an opaque 403 — a stone that went
/// dark past its grace window is welcomed back rather than stonewalled.
pub(crate) fn reject_to_response(
    assurance: &koi_common::envelope::Assurance,
) -> (StatusCode, Json<ApiErrorResponse>) {
    use koi_common::envelope::{Assurance, RejectReason};
    match assurance {
        Assurance::Rejected {
            reason: RejectReason::Expired | RejectReason::UnknownSigner,
            signer_cn,
        } => {
            // `signer_cn` is a *trusted* attribution (koi sets it only for a leaf that
            // chained to our CA but is stale) — safe to name in the prompt. An
            // unknown/unchained signer carries `None`, so we fall back generically.
            let who = signer_cn.as_deref().unwrap_or("This stone");
            error_response(
                StatusCode::UNAUTHORIZED,
                "POND_REJOIN_REQUIRED",
                format!(
                    "{who}'s pond identity is no longer valid. Rejoin to restore trust: \
                     garden-rake pond join <code>."
                ),
                None,
            )
        }
        _ => error_response(
            StatusCode::UNAUTHORIZED,
            "ENVELOPE_UNVERIFIED",
            "Request signature could not be verified.",
            None,
        ),
    }
}

/// POST /api/v1/pond/join — Join pond with TOTP code
///
/// Two modes of operation:
/// - **Cornerstone** (has CA): enrolls the stone directly via certmesh
/// - **Non-cornerstone**: discovers the cornerstone via topology, proxies the
///   enrollment request, stores the returned certificates locally, and
///   activates HTTPS + chirp signing without a restart.
///
/// Rake always sends `POST /api/v1/pond/join` to the tended stone.
/// Rake never contacts another stone directly.
pub async fn pond_join_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondJoinRequest>,
) -> PondResult<PondJoinResponse> {
    // Determine if this stone is the cornerstone (has CA initialized)
    let is_cornerstone = if let Ok(handle) = state.discovery.koi().certmesh() {
        if let Ok(core) = handle.core() {
            core.certmesh_status().await.ca_initialized
        } else {
            false
        }
    } else {
        false
    };

    if is_cornerstone {
        local_enrollment(&state, payload).await
    } else {
        proxy_enrollment(&state, payload).await
    }
}

/// Handle enrollment locally — this stone IS the cornerstone.
async fn local_enrollment(
    state: &Moss,
    payload: PondJoinRequest,
) -> PondResult<PondJoinResponse> {
    let core = get_certmesh_core(state)?;

    let hostname = payload
        .hostname
        .unwrap_or_else(|| state.current.stone.name.clone());

    // CSR-only enrollment (koi ADR-015): the joining Moss generates its own keypair
    // and sends only the CSR; the CA signs it and never sees the private key. The CSR
    // is mandatory — `core.enroll` rejects its absence — so a direct call without one
    // (e.g. `rake pond join` aimed at the already-enrolled cornerstone) cannot be honored.
    let csr = payload.csr.ok_or_else(|| {
        bad_request(
            "MISSING_CSR",
            "Enrollment requires a CSR. The joining stone's Moss generates it; \
             a direct call without one cannot be honored.",
        )
    })?;

    let join_req = koi_certmesh::protocol::JoinRequest {
        hostname: hostname.clone(),
        auth: Some(koi_crypto::auth::AuthResponse::Totp { code: payload.code }),
        invite_token: None,
        csr: Some(csr),
        sans: payload.sans,
        role: Some("member".to_string()),
    };

    let join_resp = core.enroll(&join_req).await.map_err(certmesh_err)?;

    // Determine cornerstone from the roster
    let status = core.certmesh_status().await;
    let cornerstone = status
        .members
        .iter()
        .find(|m| m.role == "primary")
        .map(|m| m.hostname.clone());

    // Notify only when the cornerstone is enrolling ITSELF. When it signs a remote
    // joiner's CSR (the normal proxy path), that remote Moss owns its own enrollment
    // lifecycle and fires its own notification — the CA must not flip its own state.
    if hostname == state.current.stone.name {
        notify_enrollment_changed(state, true, cornerstone.clone()).await;
    }

    tracing::info!(
        stone = %join_resp.hostname,
        fingerprint = %join_resp.ca_fingerprint,
        "Signed pond enrollment CSR (cornerstone)"
    );

    crate::api::ok(PondJoinResponse {
        stone_name: join_resp.hostname,
        cornerstone,
        certificate_expires: "30 days".to_string(),
        status: "active".to_string(),
        ca_fingerprint: join_resp.ca_fingerprint,
        // CSR-only: return the signed leaf + CA cert; the member already holds its key.
        ca_cert: Some(join_resp.ca_cert),
        service_cert: Some(join_resp.service_cert),
    })
}

/// Handle enrollment by proxying to the cornerstone.
///
/// Flow: Rake → this stone → cornerstone → cert issued → stored locally.
async fn proxy_enrollment(
    state: &Moss,
    payload: PondJoinRequest,
) -> PondResult<PondJoinResponse> {
    let core = get_certmesh_core(state)?;
    let hostname = state.current.stone.name.clone();

    // Discover cornerstone address via topology
    let cornerstone_addr = discover_cornerstone(state).await?;

    // CSR-only enrollment (koi ADR-015): generate our keypair + CSR locally and KEEP
    // the private key (koi writes it 0600 under certs/<hostname>/key.pem). Only the
    // public CSR crosses the wire to the cornerstone for signing.
    let csr = core
        .prepare_member_csr(&hostname, &payload.sans)
        .await
        .map_err(certmesh_err)?;

    // Forward the join request: our hostname + the CSR for the CA to sign.
    let proxy_payload = serde_json::json!({
        "code": payload.code,
        "hostname": hostname,
        "sans": payload.sans,
        "csr": csr,
    });

    tracing::info!(
        cornerstone = %cornerstone_addr,
        stone = %hostname,
        "Proxying pond join to cornerstone (CSR)"
    );

    let resp = state
        .security
        .stone_client()
        .post(&cornerstone_addr, "/api/v1/pond/join")
        .timeout(garden_common::constants::timeouts::pond_join_timeout())
        .json(&proxy_payload)
        .send()
        .await
        .map_err(|e| {
            bad_gateway(
                "CORNERSTONE_UNREACHABLE",
                format!("Failed to reach cornerstone at {cornerstone_addr}: {e}"),
            )
        })?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        // Try to forward the structured error from the cornerstone
        if let Ok(err_resp) = serde_json::from_str::<ApiErrorResponse>(&body) {
            return Err((status, Json(err_resp)));
        }
        return Err(bad_gateway(
            "CORNERSTONE_ERROR",
            format!("Cornerstone returned {status}: {body}"),
        ));
    }

    let body: serde_json::Value = resp.json().await.map_err(|e| {
        bad_gateway(
            "CORNERSTONE_PARSE_ERROR",
            format!("Failed to parse cornerstone response: {e}"),
        )
    })?;

    // Extract the join response from ApiResponse wrapper
    let data = body.get("data").ok_or_else(|| {
        bad_gateway(
            "CORNERSTONE_RESPONSE_INVALID",
            "Cornerstone response missing 'data' field".to_string(),
        )
    })?;

    let join_resp: PondJoinResponse = serde_json::from_value(data.clone()).map_err(|e| {
        bad_gateway(
            "CORNERSTONE_PARSE_ERROR",
            format!("Failed to parse join response: {e}"),
        )
    })?;

    // The CA returns the signed leaf + CA cert (never a key — we hold ours).
    let (ca_cert, service_cert) = match (&join_resp.ca_cert, &join_resp.service_cert) {
        (Some(ca), Some(cert)) => (ca.clone(), cert.clone()),
        _ => {
            return Err(bad_gateway(
                "MISSING_CERT_DATA",
                "Cornerstone did not return certificate material".to_string(),
            ));
        }
    };

    // Install the signed leaf next to our locally-held key. koi writes cert.pem,
    // ca.pem, and fullchain.pem and installs the CA root in the OS trust store. We
    // pass no CA endpoint/fingerprint: a TOFU install today, with zen-native renewal
    // (envelope-signed CSR over the clear plane) armed separately — not koi's mTLS
    // pull-renewal, which this EmbeddedOnly cornerstone does not serve.
    core.install_member_cert(
        &hostname,
        &service_cert,
        &ca_cert,
        None,
        None,
        None,
        &payload.sans,
        None,
    )
    .await
    .map_err(certmesh_err)?;

    // Mirror the CA cert to the certmesh CA path so chirp verification works on this
    // non-cornerstone stone (parity with the previous local-write path).
    let ca_cert_dest = core.paths().ca_cert_path();
    if let Some(parent) = ca_cert_dest.parent() {
        let _ = tokio::fs::create_dir_all(parent).await;
    }
    let _ = tokio::fs::write(&ca_cert_dest, &ca_cert).await;

    // Notify enrollment change — listener starts HTTPS + chirp signing
    notify_enrollment_changed(state, true, join_resp.cornerstone.clone()).await;

    tracing::info!(
        stone = %hostname,
        cornerstone = ?join_resp.cornerstone,
        fingerprint = %join_resp.ca_fingerprint,
        "Stone enrolled in pond (proxied via cornerstone)"
    );

    // Return clean response to Rake (without cert material)
    crate::api::ok(PondJoinResponse {
        stone_name: join_resp.stone_name,
        cornerstone: join_resp.cornerstone,
        certificate_expires: join_resp.certificate_expires,
        status: join_resp.status,
        ca_fingerprint: join_resp.ca_fingerprint,
        ca_cert: None,
        service_cert: None,
    })
}

/// Discover the cornerstone's address via the topology cache.
///
/// Thin HTTP wrapper over [`crate::domain::security::cornerstone::discover`] (the
/// shared walk used by both enrollment and renewal). Proxy enrollment needs only
/// the address; each discovery failure maps to its specific HTTP error code.
async fn discover_cornerstone(
    state: &Moss,
) -> Result<garden_common::PeerAddress, (StatusCode, Json<ApiErrorResponse>)> {
    use crate::domain::security::cornerstone::{self, CornerstoneError};

    match cornerstone::discover(state).await {
        Ok(found) => Ok(found.address),
        Err(e @ CornerstoneError::NoPeers) => Err(unavailable("NO_PEERS_FOUND", e.to_string())),
        Err(e @ CornerstoneError::NotInTopology { .. }) => {
            Err(unavailable("CORNERSTONE_NOT_DISCOVERED", e.to_string()))
        }
        Err(e @ CornerstoneError::NoPond) => Err(unavailable("NO_POND_FOUND", e.to_string())),
    }
}

/// POST /api/v1/pond/invite — Open enrollment and rotate auth
///
/// Rotates the TOTP secret (generating a fresh one), opens the enrollment
/// window for a limited duration, and returns the new TOTP URI for the
/// invitee to add to their authenticator app.
pub async fn pond_invite_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondInviteRequest>,
) -> PondResult<PondInviteResponse> {
    let core = get_certmesh_core(&state)?;

    // Rotate auth to get a fresh TOTP URI
    let auth_setup = core
        .rotate_auth(&payload.passphrase, None)
        .await
        .map_err(certmesh_err)?;

    // TOTP is the only auth method certmesh offers.
    let koi_crypto::auth::AuthSetup::Totp { totp_uri } = auth_setup;

    // Open the enrollment window. koi's enrollment is now a simple toggle: it
    // stays open until explicitly closed (no auto-expiry deadline). `ttl_minutes`
    // is accepted for wire-compatibility but is no longer enforced, so the invite
    // advertises no expiry.
    if payload.ttl_minutes.is_some() {
        tracing::warn!(
            "ttl_minutes is accepted for compatibility but no longer enforced — \
             enrollment stays open until explicitly closed (use pond rest/close to end it)"
        );
    }
    core.open_enrollment().await.map_err(certmesh_err)?;

    tracing::info!(
        inviter = %state.current.stone.name,
        "Pond enrollment opened with fresh invitation"
    );

    crate::api::ok(PondInviteResponse {
        totp_uri,
        expires_at: None,
        ttl_seconds: None,
        inviter_stone: state.current.stone.name.clone(),
        enrollment_state: "open".to_string(),
    })
}

/// POST /api/v1/pond/unlock — Unlock pond after restart
///
/// After a reboot, the CA private key is locked (encrypted at rest).
/// This endpoint decrypts the key so certmesh can issue/renew certificates.
///
/// Supports two unlock methods (provide exactly one):
/// - `passphrase`: traditional passphrase-based unlock
/// - `totp_code`: authenticator app code (requires TOTP unlock slot)
pub async fn pond_unlock_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondUnlockRequest>,
) -> PondResult<serde_json::Value> {
    let core = get_certmesh_core(&state)?;

    // Check if already unlocked — return idempotent no-op
    {
        let status = core.certmesh_status().await;
        if status.ca_initialized && !status.ca_locked {
            return crate::api::ok(serde_json::json!({
                "unlocked": true,
                "message": "Pond is already unlocked."
            }));
        }
    }

    if let Some(ref totp_code) = payload.totp_code {
        // TOTP-based unlock
        core.unlock_with_totp(totp_code)
            .await
            .map_err(certmesh_err)?;
        tracing::info!("Pond unlocked via TOTP code");
    } else if let Some(ref passphrase) = payload.passphrase {
        // Passphrase-based unlock (original path)
        core.unlock(passphrase).await.map_err(certmesh_err)?;
        tracing::info!("Pond unlocked via passphrase");
    } else {
        return Err(bad_request(
            "NO_UNLOCK_METHOD",
            "Provide one of: passphrase or totp_code",
        ));
    }

    // Re-derive enrolled state (CA is now unlocked → enrolled)
    refresh_pond_active(&state).await;

    // Determine cornerstone
    let cornerstone = {
        let status = core.certmesh_status().await;
        status
            .members
            .iter()
            .find(|m| m.role == "primary")
            .map(|m| m.hostname.clone())
    };

    // Notify enrollment change — listener starts HTTPS + chirp signing
    notify_enrollment_changed(&state, true, cornerstone).await;

    tracing::info!("Pond unlocked — CA key decrypted");

    crate::api::ok(serde_json::json!({
        "unlocked": true,
    }))
}

/// DELETE /api/v1/pond — Drain the pond (destroy CA)
///
/// Irreversibly destroys the CA and all certificates.
/// All enrolled stones lose their trust relationship.
pub async fn pond_remove_v1(State(state): State<Moss>) -> PondResult<serde_json::Value> {
    let core = get_certmesh_core(&state)?;

    core.destroy().await.map_err(certmesh_err)?;

    // Notify enrollment change (unenrolled) — listener stops HTTPS
    notify_enrollment_changed(&state, false, None).await;

    tracing::warn!("Pond drained — CA destroyed, all certificates invalidated");

    // Clean up pond metadata
    let path = std::path::PathBuf::from(garden_common::constants::paths::pond_metadata_file());
    let _ = std::fs::remove_file(&path);

    // Auto-unlock cleanup rides on koi's CA destroy above; any residual
    // auto-unlock vault entry is inert once the CA key is gone (and is
    // overwritten on the next pond init).

    crate::api::ok(serde_json::json!({
        "destroyed": true,
    }))
}

/// PUT /api/v1/pond/name — Rename the pond
///
/// Changes the decorative pond name without any cryptographic consequences.
/// If no name is provided, a new random name is generated.
pub async fn pond_rename_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondRenameRequest>,
) -> PondResult<serde_json::Value> {
    if !state.security.enrolled() {
        return Err(conflict(
            "POND_NOT_INITIALIZED",
            "No pond to rename. Initialize with 'garden-rake place keystone' first.",
        ));
    }

    let new_name = match payload.name {
        Some(ref name) if crate::domain::naming::is_valid_pond_name(name) => name.clone(),
        Some(ref name) if !name.is_empty() => {
            return Err(bad_request(
                "INVALID_POND_NAME",
                format!("Pond name must match 'pond-{{word}}-{{word}}' format, got: '{name}'"),
            ));
        }
        _ => crate::domain::naming::generate_pond_name(),
    };

    state.security.set_pond_name(new_name.clone()).await;
    let metadata = crate::domain::PondMetadata {
        name: Some(new_name.clone()),
    };
    if let Err(e) = crate::domain::save_pond_metadata(&metadata) {
        tracing::warn!(error = %e, "Failed to persist pond metadata");
    }

    tracing::info!(name = %new_name, "Pond renamed");

    crate::api::ok(serde_json::json!({
        "name": new_name,
    }))
}

/// DELETE /api/v1/pond/stones/{stone_name} — Untrust a stone (revoke certificate)
pub async fn pond_untrust_v1(
    State(state): State<Moss>,
    Path(stone_name): Path<String>,
) -> PondResult<serde_json::Value> {
    let core = get_certmesh_core(&state)?;

    core.revoke_member(&stone_name, None, Some("Untrusted via API".to_string()))
        .await
        .map_err(certmesh_err)?;

    tracing::info!(stone = %stone_name, "Stone revoked from pond");

    crate::api::ok(serde_json::json!({
        "revoked": true,
        "stone_name": stone_name,
    }))
}

/// POST /api/v1/pond/promote — Promote this stone to standby CA
pub async fn pond_promote_v1(
    State(state): State<Moss>,
    Json(payload): Json<PondPromoteRequest>,
) -> PondResult<serde_json::Value> {
    let core = get_certmesh_core(&state)?;

    let key_bytes: [u8; 32] = hex::decode(&payload.client_public_key)
        .map_err(|e| {
            certmesh_err(koi_certmesh::CertmeshError::Internal(format!(
                "invalid client_public_key hex: {e}"
            )))
        })?
        .try_into()
        .map_err(|_| {
            certmesh_err(koi_certmesh::CertmeshError::Internal(
                "client_public_key must be exactly 32 bytes".to_string(),
            ))
        })?;

    let _resp = core.promote(&key_bytes).await.map_err(certmesh_err)?;

    tracing::info!(
        stone = %state.current.stone.name,
        "Stone promoted — received CA key material"
    );

    crate::api::ok(serde_json::json!({
        "promoted": true,
        "ca_fingerprint": koi_certmesh::ca::ca_fingerprint_from_disk(core.paths())
            .unwrap_or_else(|_| "unavailable".to_string()),
    }))
}

/// GET /api/v1/pond/ca.pem — Download CA public certificate
///
/// Serves the CA public certificate for manual trust installation
/// on non-enrolled machines (e.g., browsers, phones).
pub async fn pond_ca_cert_v1(
    State(state): State<Moss>,
) -> Result<(StatusCode, [(String, String); 1], String), (StatusCode, Json<ApiErrorResponse>)> {
    let core = get_certmesh_core(&state)?;
    let status = core.certmesh_status().await;

    if !status.ca_initialized {
        return Err(not_found(
            "POND_NOT_INITIALIZED",
            "No pond CA exists. Run 'garden-rake place keystone' first.",
        ));
    }

    // Read CA cert from disk
    let ca_cert_path = core.paths().ca_cert_path();
    let ca_pem = tokio::fs::read_to_string(&ca_cert_path)
        .await
        .map_err(|e| {
            internal(
                "CA_READ_ERROR",
                format!("Failed to read CA certificate: {e}"),
            )
        })?;

    Ok((
        StatusCode::OK,
        [(
            "content-type".to_string(),
            "application/x-pem-file".to_string(),
        )],
        ca_pem,
    ))
}

// ============================================================================
// Ceremony
// ============================================================================

/// POST /api/v1/pond/ceremony — Step through a pond ceremony
///
/// This endpoint drives pond ceremonies (init, join, invite, unlock)
/// using the koi-common ceremony protocol. Each request either starts
/// a new ceremony or continues an existing session.
///
/// When the "init" ceremony completes, the handler automatically
/// creates the CA using the collected bag data.
pub async fn pond_ceremony_v1(
    State(state): State<Moss>,
    Json(request): Json<koi_common::ceremony::CeremonyRequest>,
) -> Result<Json<koi_common::ceremony::CeremonyResponse>, (StatusCode, Json<ApiErrorResponse>)> {
    let host = state.security.ceremony_host();

    // Pre-fill hostname for TOTP personalization
    let mut req = request;
    if req.ceremony.as_deref() == Some("init") && req.session_id.is_none() {
        req.data
            .entry("_self_hostname".to_string())
            .or_insert_with(|| serde_json::json!(state.current.stone.name));
    }

    let response = host
        .step(req)
        .map_err(|e| bad_request("CEREMONY_ERROR", format!("{e}")))?;

    // When an init ceremony completes, execute the CA creation
    if response.complete && response.error.is_none() {
        let is_init = response
            .result_data
            .as_ref()
            .map(|d| d.contains_key("_effective_profile") && d.contains_key("passphrase"))
            .unwrap_or(false);
        if is_init {
            return execute_pond_init_from_ceremony(&state, response).await;
        }

        // When an unlock ceremony completes, execute the unlock
        let is_unlock = response
            .result_data
            .as_ref()
            .map(|d| {
                d.contains_key("passphrase") || d.contains_key("_unlock_totp_input")
            })
            .unwrap_or(false);
        if is_unlock {
            return execute_pond_unlock_from_ceremony(&state, response).await;
        }
    }

    Ok(Json(response))
}

/// Execute pond initialization using data collected by the ceremony,
/// then return the ceremony response with creation details attached.
async fn execute_pond_init_from_ceremony(
    state: &Moss,
    mut response: koi_common::ceremony::CeremonyResponse,
) -> Result<Json<koi_common::ceremony::CeremonyResponse>, (StatusCode, Json<ApiErrorResponse>)> {
    let bag = response.result_data.as_ref().ok_or_else(|| {
        internal(
            "CEREMONY_ERROR",
            "Init ceremony completed with no result data",
        )
    })?;
    let core = get_certmesh_core(state)?;

    // Trust profile flattened to two booleans: resolve the named preset, then
    // let any explicit ceremony overrides win.
    let effective_profile = bag
        .get("_effective_profile")
        .and_then(|v| v.as_str())
        .unwrap_or("just_me");
    let (preset_open, preset_approval, preset_auto_unlock) =
        koi_certmesh::profiles::preset_bools(effective_profile).unwrap_or_else(|| {
            tracing::warn!(
                profile = effective_profile,
                "Unrecognized trust profile preset — defaulting to just-me"
            );
            (true, false, true)
        });

    let passphrase = bag
        .get("passphrase")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    let entropy_hex = bag
        .get("_entropy_seed")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    let operator = bag
        .get("operator")
        .and_then(|v| v.as_str())
        .map(String::from);
    let enrollment_open = bag
        .get("_enrollment_open")
        .and_then(|v| v.as_bool())
        .unwrap_or(preset_open);
    let requires_approval = bag
        .get("_requires_approval")
        .and_then(|v| v.as_bool())
        .unwrap_or(preset_approval);
    let totp_secret_hex = bag
        .get("_totp_secret_hex")
        .and_then(|v| v.as_str())
        .map(String::from);

    // Auto-unlock is the preset's choice, but only when the user kept the
    // automatic unlock method (a token unlock means manual/token unlock instead).
    let auto_unlock = preset_auto_unlock
        && bag
            .get("_unlock_method")
            .and_then(|v| v.as_str())
            .unwrap_or("auto")
            == "auto";

    let create_req = koi_certmesh::protocol::CreateCaRequest {
        passphrase,
        entropy_hex,
        operator,
        enrollment_open,
        requires_approval,
        auto_unlock,
        totp_secret_hex,
    };

    let body = serde_json::to_vec(&create_req).map_err(|e| {
        internal(
            "SERIALIZE_ERROR",
            format!("Failed to build certmesh request: {e}"),
        )
    })?;

    let http_req = axum::http::Request::builder()
        .method("POST")
        .uri("/create")
        .header("content-type", "application/json")
        .body(axum::body::Body::from(body))
        .expect("valid request");

    let http_resp = core
        .http_routes()
        .oneshot(http_req)
        .await
        .expect("Router is infallible");

    let status_code = http_resp.status();
    let resp_bytes = axum::body::to_bytes(http_resp.into_body(), 1024 * 1024)
        .await
        .map_err(|e| {
            internal(
                "RESPONSE_READ_ERROR",
                format!("Failed to read certmesh response: {e}"),
            )
        })?;

    if !status_code.is_success() {
        let error_text = String::from_utf8_lossy(&resp_bytes);
        tracing::error!(
            status = %status_code,
            body = %error_text,
            "Certmesh CA creation failed (ceremony)"
        );
        response.error = Some(format!("Pond creation failed: {error_text}"));
        return Ok(Json(response));
    }

    let create_resp: koi_certmesh::protocol::CreateCaResponse = serde_json::from_slice(&resp_bytes)
        .map_err(|e| {
            internal(
                "PARSE_ERROR",
                format!("Failed to parse certmesh response: {e}"),
            )
        })?;

    // Update pond state
    refresh_pond_active(state).await;

    // ── Unlock method ───────────────────────────────────────────────
    // Auto-unlock is configured inside CertmeshCore::create() from the request's
    // `auto_unlock` flag. A token unlock (TOTP) is registered separately below
    // because it needs ceremony-specific data from the bag.
    let unlock_method = bag
        .get("_unlock_method")
        .and_then(|v| v.as_str())
        .unwrap_or("auto");
    let passphrase_for_file = bag.get("passphrase").and_then(|v| v.as_str()).unwrap_or("");

    // Set when a TOTP unlock slot was requested but could not be created — the
    // lean build has no OS credential store to seal the secret in. Surfaced to
    // the user as a clear, non-fatal message once the `bag` borrow is released,
    // so they are not left with a scanned TOTP QR for a slot that never existed.
    let mut totp_unlock_unavailable = false;

    match unlock_method {
        "auto" => {
            // Auto-unlock was already configured inside CertmeshCore::create()
            // from the request's `auto_unlock` flag (koi's single source of truth).
        }
        "token" => {
            let token_type = bag
                .get("unlock_token_type")
                .and_then(|v| v.as_str())
                .unwrap_or("totp");

            let slot_table_path = core.paths().slot_table_path();
            if !slot_table_path.exists() {
                tracing::error!(
                    "Slot table not found after CA creation — cannot register unlock token"
                );
            } else {
                match koi_crypto::unlock_slots::SlotTable::load(&slot_table_path) {
                    Ok(mut table) => {
                        // Unwrap master key with passphrase to add the new slot
                        match table.unwrap_with_passphrase(passphrase_for_file) {
                            Ok(master_key) => {
                                match token_type {
                                    "totp" => {
                                        // TOTP unlock slots seal the shared secret in the OS
                                        // credential store. On a lean build (no koi `keyring`
                                        // feature) that store is absent, so the slot cannot be
                                        // created — skip the attempt and flag it, rather than
                                        // accept a scanned QR for a slot that will never exist.
                                        if !koi_crypto::tpm::is_available() {
                                            totp_unlock_unavailable = true;
                                            tracing::warn!(
                                                "TOTP unlock requested but no OS credential store is available on this build — skipping slot; pond uses passphrase unlock"
                                            );
                                        } else if let Some(secret_hex) =
                                            bag.get("_unlock_totp_secret").and_then(|v| v.as_str())
                                        {
                                            match koi_common::encoding::hex_decode(secret_hex) {
                                                Ok(secret_bytes) => {
                                                    match table
                                                        .add_totp_slot(&master_key, &secret_bytes)
                                                    {
                                                        Ok(()) => {
                                                            if let Err(e) =
                                                                table.save(&slot_table_path)
                                                            {
                                                                tracing::error!(error = %e, "Failed to save slot table after adding TOTP slot");
                                                            } else {
                                                                tracing::info!(
                                                                    "TOTP unlock slot registered — pond can be unlocked with authenticator code"
                                                                );
                                                            }
                                                        }
                                                        Err(e) => {
                                                            totp_unlock_unavailable = true;
                                                            tracing::error!(error = %e, "Failed to add TOTP unlock slot")
                                                        }
                                                    }
                                                }
                                                Err(e) => {
                                                    tracing::error!(error = %e, "Invalid _unlock_totp_secret hex")
                                                }
                                            }
                                        } else {
                                            tracing::error!(
                                                "Token type is TOTP but _unlock_totp_secret is missing from ceremony bag"
                                            );
                                        }
                                    }
                                    other => {
                                        tracing::warn!(
                                            token_type = other,
                                            "Unknown unlock token type — no slot created"
                                        );
                                    }
                                }
                            }
                            Err(e) => {
                                tracing::error!(error = %e, "Failed to unwrap master key for token slot creation")
                            }
                        }
                    }
                    Err(e) => {
                        tracing::error!(error = %e, "Failed to load slot table for token registration")
                    }
                }
            }
        }
        // "passphrase" or anything else → no auto-unlock, no token
        _ => {
            tracing::info!(
                "Unlock method is '{unlock_method}' — no auto-unlock key or token registered"
            );
        }
    }

    let pond_name = crate::domain::naming::generate_pond_name();
    state.security.set_pond_name(pond_name.clone()).await;
    let metadata = crate::domain::PondMetadata {
        name: Some(pond_name.clone()),
    };
    if let Err(e) = crate::domain::save_pond_metadata(&metadata) {
        tracing::warn!(error = %e, "Failed to persist pond metadata");
    }

    notify_enrollment_changed(state, true, Some(state.current.stone.name.clone())).await;

    tracing::info!(
        cornerstone = %state.current.stone.name,
        pond_name = %pond_name,
        profile = %effective_profile,
        enrollment_open,
        requires_approval,
        auto_unlock,
        fingerprint = %create_resp.ca_fingerprint,
        "Pond initialized via ceremony — keystone placed"
    );

    // Sanitize result_data — strip secrets, add creation results
    let mut safe_data = serde_json::Map::new();
    safe_data.insert("pond_name".into(), serde_json::json!(pond_name));
    safe_data.insert(
        "ca_fingerprint".into(),
        serde_json::json!(create_resp.ca_fingerprint),
    );
    safe_data.insert(
        "cornerstone".into(),
        serde_json::json!(state.current.stone.name),
    );
    safe_data.insert("profile".into(), serde_json::json!(effective_profile));
    response.result_data = Some(safe_data);

    // If a TOTP unlock slot was requested but couldn't be created on this build,
    // tell the user plainly — the pond is created and unlockable by passphrase.
    if totp_unlock_unavailable {
        response.messages.push(koi_common::ceremony::Message {
            kind: koi_common::ceremony::MessageKind::Error,
            title: "TOTP unlock unavailable".to_string(),
            content: "This stone has no OS credential store, so an authenticator (TOTP) \
                      unlock could not be configured. The pond was created — unlock it \
                      with your passphrase."
                .to_string(),
        });
    }

    Ok(Json(response))
}

// ============================================================================
// Ceremony-driven unlock
// ============================================================================

/// Execute pond unlock using data collected by the unlock ceremony.
async fn execute_pond_unlock_from_ceremony(
    state: &Moss,
    mut response: koi_common::ceremony::CeremonyResponse,
) -> Result<Json<koi_common::ceremony::CeremonyResponse>, (StatusCode, Json<ApiErrorResponse>)> {
    let bag = response.result_data.as_ref().ok_or_else(|| {
        internal(
            "CEREMONY_ERROR",
            "Unlock ceremony completed with no result data",
        )
    })?;
    let core = get_certmesh_core(state)?;

    let unlock_result =
        if let Some(totp_code) = bag.get("_unlock_totp_input").and_then(|v| v.as_str()) {
            core.unlock_with_totp(totp_code).await
        } else if let Some(passphrase) = bag.get("passphrase").and_then(|v| v.as_str()) {
            core.unlock(passphrase).await
        } else {
            return Err(bad_request(
                "NO_UNLOCK_METHOD",
                "Unlock ceremony completed without any unlock credential",
            ));
        };

    match unlock_result {
        Ok(()) => {
            refresh_pond_active(state).await;

            // Determine cornerstone
            let cornerstone = {
                let status = core.certmesh_status().await;
                status
                    .members
                    .iter()
                    .find(|m| m.role == "primary")
                    .map(|m| m.hostname.clone())
            };
            notify_enrollment_changed(state, true, cornerstone).await;

            tracing::info!("Pond unlocked via ceremony");

            // Sanitize result_data — strip secrets
            let mut safe_data = serde_json::Map::new();
            safe_data.insert("unlocked".into(), serde_json::json!(true));
            response.result_data = Some(safe_data);
        }
        Err(e) => {
            tracing::warn!(error = %e, "Pond unlock failed via ceremony");
            response.error = Some(format!("Unlock failed: {e}"));
        }
    }

    Ok(Json(response))
}

// Auto-unlock key management now lives in koi-certmesh domain:
//   CertmeshCore::save_auto_unlock_key()
//   CertmeshCore::delete_auto_unlock_key()
//   CertmeshCore::try_auto_unlock()
//   CertmeshCore::configure_auto_unlock_for_profile()
