"""
Open Iconic bitmaps for Firefly OLED v2.

Auto-generated by firmware/firefly/tools/convert_icons.py
Do not edit by hand — re-run the converter to regenerate.

Source: https://github.com/iconic/open-iconic
License: MIT (icons), SIL OFL 1.1 (font form)

Each icon is an 8-byte MSB-left bitmap (8x8 pixels).
"""

# pulse.png
ICON_CPU = bytearray([
    0x00,  # ........
    0x10,  # ...#....
    0x30,  # ..##....
    0x3C,  # ..####..
    0xEF,  # ###.####
    0x68,  # .##.#...
    0x00,  # ........
    0x00,  # ........
])

# layers.png
ICON_MEM = bytearray([
    0xF0,  # ####....
    0xF0,  # ####....
    0xF4,  # ####.#..
    0xF4,  # ####.#..
    0x05,  # .....#.#
    0x3D,  # ..####.#
    0x01,  # .......#
    0x0F,  # ....####
])

# hard-drive.png
ICON_DSK = bytearray([
    0xFE,  # #######.
    0xFE,  # #######.
    0xFE,  # #######.
    0xFE,  # #######.
    0x00,  # ........
    0xFE,  # #######.
    0xFA,  # #####.#.
    0xFE,  # #######.
])

# bolt.png
ICON_USB = bytearray([
    0x00,  # ........
    0x10,  # ...#....
    0x30,  # ..##....
    0x3C,  # ..####..
    0x78,  # .####...
    0x10,  # ...#....
    0x10,  # ...#....
    0x00,  # ........
])

# cog.png
ICON_GEAR = bytearray([
    0x18,  # ...##...
    0x7E,  # .######.
    0x7E,  # .######.
    0xE7,  # ###..###
    0xE7,  # ###..###
    0x7E,  # .######.
    0x7E,  # .######.
    0x18,  # ...##...
])

# data-transfer-download.png
ICON_NET_DOWN = bytearray([
    0x18,  # ...##...
    0x18,  # ...##...
    0x18,  # ...##...
    0x7E,  # .######.
    0x3C,  # ..####..
    0x18,  # ...##...
    0x00,  # ........
    0xFF,  # ########
])

# data-transfer-upload.png
ICON_NET_UP = bytearray([
    0xFF,  # ########
    0x00,  # ........
    0x18,  # ...##...
    0x3C,  # ..####..
    0x7E,  # .######.
    0x18,  # ...##...
    0x18,  # ...##...
    0x18,  # ...##...
])

# globe.png
ICON_NET = bytearray([
    0x3C,  # ..####..
    0x66,  # .##..##.
    0xC7,  # ##...###
    0x87,  # #....###
    0x8F,  # #...####
    0xC3,  # ##....##
    0x62,  # .##...#.
    0x3C,  # ..####..
])

# clock.png
ICON_CLOCK = bytearray([
    0x3C,  # ..####..
    0x42,  # .#....#.
    0x81,  # #......#
    0x91,  # #..#...#
    0x89,  # #...#..#
    0x81,  # #......#
    0x42,  # .#....#.
    0x3C,  # ..####..
])

# grid-three-up.png
ICON_STONES = bytearray([
    0xDB,  # ##.##.##
    0xDB,  # ##.##.##
    0x00,  # ........
    0xDB,  # ##.##.##
    0xDB,  # ##.##.##
    0x00,  # ........
    0xDB,  # ##.##.##
    0xDB,  # ##.##.##
])

# heart.png
ICON_THRIVING = bytearray([
    0x00,  # ........
    0x66,  # .##..##.
    0xFF,  # ########
    0xFF,  # ########
    0x7E,  # .######.
    0x3C,  # ..####..
    0x18,  # ...##...
    0x00,  # ........
])

# warning.png
ICON_WITHERING = bytearray([
    0x10,  # ...#....
    0x38,  # ..###...
    0x38,  # ..###...
    0x68,  # .##.#...
    0x6C,  # .##.##..
    0x7C,  # .#####..
    0xEE,  # ###.###.
    0xFE,  # #######.
])

# circle-x.png
ICON_WILTING = bytearray([
    0x3C,  # ..####..
    0x7E,  # .######.
    0xDB,  # ##.##.##
    0xE7,  # ###..###
    0xE7,  # ###..###
    0xDB,  # ##.##.##
    0x7E,  # .######.
    0x3C,  # ..####..
])
