[package]
name = "garden-room"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
garden-glossary.workspace = true
garden-contract.workspace = true
chrono.workspace = true
if-addrs.workspace = true
parking_lot = "0.12"
serde.workspace = true
serde_json.workspace = true
socket2 = "0.6"
tokio.workspace = true
tokio-util = "0.7"
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
