#!/bin/bash
# Garden Rake Quick Reference for Stone
# This file is automatically created during Stone installation

echo "╔════════════════════════════════════════════════════╗"
echo "║        Zen Garden - garden-rake Commands          ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "BASICS:"
echo "  garden-rake status            # Check stone health"
echo "  garden-rake list              # List installed services"
echo "  garden-rake offer <service>   # Install a service"
echo ""
echo "REAL-TIME MONITORING:"
echo "  garden-rake watch                      # Watch all events"
echo "  garden-rake watch --until 'pattern'    # Exit when pattern matches"
echo ""
echo "EXAMPLES:"
echo "  # Monitor installation progress"
echo "  garden-rake watch --until 'successfully'"
echo ""
echo "  # Watch while installing a service"
echo "  # Terminal 1:"
echo "  garden-rake watch"
echo "  # Terminal 2:"
echo "  garden-rake offer mongodb"
echo ""
echo "AVAILABLE SERVICES:"
echo "  mongodb, postgresql, redis, vault, weaviate, milvus,"
echo "  qdrant, typesense, clickhouse, minio, valkey, elasticsearch"
echo ""
echo "For full help: garden-rake --help"
echo ""
