[package]
name = "garden-common"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yml.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros", "fs", "io-util", "net", "process", "signal"] }
chrono = { workspace = true, features = ["serde"] }
thiserror.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
anyhow.workspace = true
async-stream.workspace = true
tokio-stream.workspace = true
futures.workspace = true
futures-util.workspace = true
uuid.workspace = true
blake3.workspace = true
tracing.workspace = true
socket2.workspace = true
if-addrs.workspace = true
sysinfo.workspace = true
regex.workspace = true
walkdir.workspace = true
rand.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_Networking_WinSock", "Win32_Storage_FileSystem"] }
windows = { version = "0.52", features = ["Win32_Graphics_Dxgi"] }

[dev-dependencies]
tempfile.workspace = true
proptest = "1"

[lints]
workspace = true

[lib]
path = "src/lib.rs"
